apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false 
    argocd.argoproj.io/sync-wave: "-1"    
  name: sealed-secrets-operator-helm
  namespace: sealed-secrets
spec:
  targetNamespaces:
  - sealed-secrets