kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: 'true'
  statusbadge.enabled: 'false'
  resource.exclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  ga.trackingid: ''
  repositories: ''
  ga.anonymizeusers: 'false'
  help.chatUrl: ''
  # url: >-
  #   https://openshift-gitops-server-openshift-gitops.apps.cluster-0602.sandbox392.opentlc.com
  help.chatText: ''
  kustomize.buildOptions: ''
  resource.inclusions: ''
  repository.credentials: ''
  users.anonymous.enabled: 'false'
  configManagementPlugins: ''
  application.instanceLabelKey: ''

  resource.customizations.health.bitnami.com_SealedSecret: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Controller doesn't report resource status"
    return hs

