kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    route.openshift.io/termination: "edge"
    "helm.sh/hook-weight": "3"
  name: sealed-secrets-ingress
  namespace: sealed-secrets
spec:
  rules:
    - host: paas-{{ .Values.clusterid }}.sealed-secrets.paas.net.intra.laposte.fr
      http:
        paths:
          - backend:
              serviceName: sealedsecretcontroller-sealed-secrets
              servicePort: 8080
  tls:
    - hosts:
        - paas-{{ .Values.clusterid }}.sealed-secrets.paas.net.intra.laposte.fr
      secretName: sealed-secrets-pki

