---
apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: argocd-vault-plugin-demo1
  namespace: openshift-gitops
  labels:
    gitops: argocd-vault-plugin
spec:
  project: default
  source:
    repoURL: https://github.com/lcolagio/lab-gitops-ops
    path: draft/argocd-vault-plugin/base
  destination:
    name: demo1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
