---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
-  target:
     kind: Subscription
     name: openshift-gitops-operator
   path: dex-subscription-patch.yaml

patches:
-  target:
     kind: argocd
     group: argoproj.io
     name: openshift-gitops
   path: dex-argocd-patch.yaml

-  target:
     kind: ConfigMap
     name: argocd-cm
   path: repo-patch.yaml


# patches:
# -  target:
#      kind: Subscription
#      name: openshift-gitops-operator
#    patch: |-
#     - op: replace
#       path: /spec/channel
#       value: 'stable'

#     - op: add
#       path: /spec/config
#       value: 
#         env:
#           - name: DISABLE_DEX
#             value: 'false'

# -  target:
#      kind: ConfigMap
#      name: argocd-cm
#    patch: |-
#     - op: add
#       path: /data
#       value: 
#         repositories: |
#           - name: git1
#             type: git
#             url: https://github.com/lcolagio/lab-gitops-ops