- op: add
  path: /data
  value: 
    repositories: |
      - name: git1
        type: git
        url: https://github.com/lcolagio/lab-gitops-ops

      - name: git2
        type: git
        url: https://github.com/lcolagio/lab-vault-plugin
