- op: add
  path: /data
  value: 
    repositories: |
      - name: git1
        type: git
        url: https://github.com/lcolagio/lab-gitops-ops

# - op: add
#   path: /data
#   value: 
#     repositories: |
      - name: git-lab-vault-plugin
        type: git
        url: https://github.com/lcolagio/lab-vault-plugin